set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_PREFIX "$ENV{MINGW_PREFIX}")
if(MINGW_PREFIX)
    file(TO_CMAKE_PATH "${MINGW_PREFIX}" MINGW_PREFIX)
else()
    set(MINGW_PREFIX "/usr/x86_64-w64-mingw32")
endif()

set(COMPILER_TRIPLE "x86_64-w64-mingw32")
set(CMAKE_C_COMPILER "${MINGW_PREFIX}/bin/${COMPILER_TRIPLE}-gcc" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER "${MINGW_PREFIX}/bin/${COMPILER_TRIPLE}-g++" CACHE FILEPATH "")
set(CMAKE_RC_COMPILER "${MINGW_PREFIX}/bin/${COMPILER_TRIPLE}-windres" CACHE FILEPATH "")

set(CMAKE_C_COMPILER_TARGET "${COMPILER_TRIPLE}" CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET "${COMPILER_TRIPLE}" CACHE STRING "")

set(CMAKE_FIND_ROOT_PATH
    "${MINGW_PREFIX}"
    "${MINGW_PREFIX}/${COMPILER_TRIPLE}"
    CACHE STRING ""
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
